DeleteFileById endpoint
LT-Students/DigitalOffice-FileService pull request #5
Opened 2020-10-12 22:24 UTC by lalagvana

Added DeleteFileById method and updated packages.

2020-10-12 23:25 UTC, DarkFelas requested changes

2020-10-12 23:25 UTC, DarkFelas commented on src/FileService.Data/FileRepository.cs
> +            provider.Files.Remove(dbFile);
Rework, IsActive = false

2020-10-13 14:18 UTC, djino97 approved these changes

2020-10-13 14:18 UTC, djino97 commented on src/FileService/FileService.csproj
> +    <PackageReference Include="MassTransit.RabbitMQ" Version="7.0.4" />
remove

2020-10-13 14:18 UTC, djino97 commented on test/FileService.Business.UnitTests/DeleteFileByIdCommandTests.cs
> +        public void ShouldDeleteFile()
DisabledFile

2020-10-13 14:18 UTC, djino97 commented on src/FileService/Controllers/FileController.cs
> +        [HttpDelete("deleteFileById")]
disableFileById

2020-10-13 14:18 UTC, djino97 commented on src/FileService.Broker/FileService.Broker.csproj
>      <PackageReference Include="MassTransit" Version="7.0.4" />
remove

2020-10-21 17:59 UTC, DarkFelas approved these changes

2020-10-21 18:02 UTC, merged